services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '54320:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-app_db}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - romashka-network

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: rabbitmq
    volumes:
      - ./infrastructure/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"'
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Web UI (management plugin)
    networks:
      - romashka-network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase
    volumes:
      - ./resources/db/changelog/changelog-master.xml:/liquibase/changelog-master.xml
      - ./resources/db/changelog/v.0.0.2:/liquibase/v.0.0.2
      - ./resources/db/changelog/v.0.0.3:/liquibase/v.0.0.3
      - ./resources/db/changelog/v.0.0.4:/liquibase/v.0.0.4
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - romashka-network
    command: --url="jdbc:postgresql://postgres_db:5432/${DB_NAME}" --username=${DB_USER} --password=${DB_PASSWORD} --changeLogFile=changelog-master.xml update

  cdr:
    build: CDR/
    container_name: cdr
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - romashka-network
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  brt:
    build: BRT/
    container_name: brt
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - romashka-network
    ports:
      - "8081:8081"

  hrs:
    build: HRS/
    container_name: hrs
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - romashka-network
    ports:
      - "8082:8082"

  crm:
    build: CRM/
    container_name: crm
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - romashka-network
    ports:
      - "8083:8083"

networks:
  romashka-network:
    driver: bridge

volumes:
  db-data: