spring:
  rabbitmq:
    queue:
      name: cdr.queue
    exchange:
      name: cdr.direct
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    routing:
      key: cdr
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dbapp
    driverClassName: org.h2.Driver
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: embedded

