name: Java CI with Build, Test, Jacoco and SonarQube
on:
  push:
    branches:
      - main, dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build, Test, Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      
      - name: Build and run tests with coverage
        run: |
          ./gradlew clean test
          ./gradlew jacocoTestReport
          find . -name "jacoco*" -o -name "*.exec" -o -name "*.xml"
          ls -la build/reports/jacoco/test/ || true
          ls -la build/jacoco/ || true
      
      - name: SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_COVERAGE_JACOCO_XML_REPORT_PATHS: build/reports/jacoco/test/jacocoTestReport.xml
        run: |
          echo "Running SonarQube with Jacoco report from: $SONAR_COVERAGE_JACOCO_XML_REPORT_PATHS"
          ./gradlew sonar \
            -Dsonar.coverage.jacoco.xmlReportPaths=$SONAR_COVERAGE_JACOCO_XML_REPORT_PATHS \
            --info
